# Generated by Django 3.1.4 on 2020-12-22 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Karyawan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_karyawan', models.CharField(max_length=20)),
                ('nama_karyawan', models.CharField(max_length=100)),
                ('email_karyawan', models.EmailField(max_length=254)),
                ('kontak_karyawan', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'karyawan',
            },
        ),
    ]
